### ISSUE TITLE
Need an answer

### ISSUE THREAD

**Issue by noreta** [afivos/afivos.com#2]
I'm in love with this theme, can I use it ?? how ??

**Comment by afivos** [comment]
Oh, I'm flattered! So sorry I missed your message and it took me a month to reply. I see you did a great job in using it, though. Was it easy? What did you actually do? :)

**Comment by noreta** [comment]
Thank you first and surely no problem about the reply. I just made a little modifications to make it runs on gh-pages even though I'm not hosting it on the gh-pages server. I host it on Firebase, probably you have seen it from the travis.yml :smile: [https://blog-b4aae.firebaseapp.com/](https://blog-b4aae.firebaseapp.com/) the speed is awesome.

**Comment by afivos** [comment]
That's great to hear! I might give it a try sometime soon. :)
